language: cpp
git:
  submodules: false
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo add-apt-repository --yes ppa:beineri/opt-qt55
  - sudo apt-add-repository --yes ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8 libsamplerate0-dev
  - sudo apt-get install -qq -y qt55base qt55declarative qt55imageformats qt55location qt55multimedia qt55qbs qt55quickcontrols qt55script qt55tools qt55translations libsdl2-dev
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
script:
  - source /opt/qt55/bin/qt55-env.sh
  - mkdir phoenix-build
  - cd phoenix-build
  - qmake ..
  - make
notifications:
  irc:
    channels:
      - "chat.freenode.net#phoenix-dev"
    use_notice: true
    skip_join: true
